version: 2.1
jobs:
  install:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "installing the app"
      - run: npm install
  playing:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hello"
workflows: 
  version: 2
  builds: 
    jobs: 
    - install
    - playing