version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Building the app"
      - run: npm install
      - run: CI=true npm run build
  playing:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hello"
workflows: 
  version: 2
  builds: 
    jobs: 
    - build
    - playing